### ISSUE TITLE
Regular animals not spawning

### ISSUE THREAD

**Issue by kreezxil** [SaemonMoki/ExtendedAnimals#7]
this is my config
```toml
[general]

	[general.wildType]
		# 100 will make all animals spawn as wildtype for their biome, some mutations may be impossible to get. 0 makes animals spawn with almost completely random genes. higher numbers are best since you only need a few mutations to make a big difference
		#Range: > 1
		chance = 90

	[general.spawnVanillaMobs]
		#Set this to true to allow vanilla minecraft mobs to continue to spawn. False will prevent their spawning and only spawn Eanimod versions
		enabled = true

	[general.gestation]
		#Number of ticks for pig gestation. 48000 = 2 Minecraft Days
		#Range: > 1
		days = 48000

```
**I would like to point out** that when vanillaMobs was set to false, not even your animals spawned. Then I set it to true and then your animals spawned. 

Using build 0.4.7 on Forge 28.1.31
